#!/usr/bin/env python3

import RPi.GPIO as GPIO
import time

GPIO.setmode(GPIO.BCM)

#init list with pin

PinList = [2,3,4,17]
PinList = [17]
for p in PinList:
	GPIO.setup(p, GPIO.OUT)
	GPIO.output(p, GPIO.HIGH)
	
#sleep time

SleepTime = 10

try:
	for p in PinList:
		GPIO.output(p, GPIO.LOW)
		print("Pin {} is on.".format(p))
		time.sleep(SleepTime)
		#High turns the pins off.
		GPIO.output(p, GPIO.HIGH)
		print("Pin {} is off.".format(p))
		time.sleep(SleepTime)
		
	GPIO.cleanup()
	print("Done all pins are off")
except KeyboardInterrupt:
	print("\n\tCommand from Keyboard  to Quit")
	GPIO.cleanup()
except Exception as e:
	print("An error has occured\n\t{}".format(e))
	
	GPIO.cleanup()
	
